@startuml
interface n1
enum n2
enum n3
enum n4
enum n5
class n6 as "tests\graph\tsg\cpp\includes\main.cpp"
enum n7
enum n8
abstract n9 as "tests\graph\tsg\cpp\includes\main.hh"
enum n10
enum n11
enum n12
enum n13
enum n14
enum n15
enum n16
enum n17
enum n18 as "main"
enum n19 as "main"
enum n20
enum n21
enum n22
enum n23
enum n24
enum n25
class n26 as "tests\graph\tsg\cpp\includes\main.hh"
enum n27
enum n28
enum n29
enum n30
enum n31 as "MAIN_HH"
enum n32 as "MAIN_HH"
enum n33
enum n34
enum n35
enum n36
enum n37 as "MAIN_HH"
enum n38 as "MAIN_HH"
enum n39
enum n40
enum n41
enum n42
enum n43
class n44 as "main"
enum n45 as "main"
enum n46
enum n47
enum n48
n1 ---> n6
n1 ---> n26
n3 ---> n1
n3 ---> n4
n4 ---> n8
n4 ---> n11
n4 ---> n14
n6 ---> n3
n7 ---> n3
n7 ---> n8
n8 ---> n9
n9 ---> n1
n10 ---> n3
n10 ---> n11
n13 ---> n3
n13 ---> n14
n17 ---> n18
n19 ---> n17
n20 ---> n21
n23 ---> n1
n23 ---> n24
n24 ---> n28
n26 ---> n23
n27 ---> n23
n27 ---> n28
n28 ---> n34
n28 ---> n40
n30 ---> n31
n32 ---> n30
n33 ---> n27
n33 ---> n34
n36 ---> n37
n38 ---> n36
n39 ---> n27
n39 ---> n40
n40 ---> n44
n42 ---> n39
n43 ---> n44
n44 ---> n42
n44 ---> n47
n45 ---> n43
n46 ---> n39
n46 ---> n47
@enduml
